/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sheltertest;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        VirtualPetShelter shelter = new VirtualPetShelter();

        System.out.println("Thank you for volunteering at Big Al's Virtual Pet Shelter and Delicatessen!");

        // pets
        shelter.intakePet(new VirtualPet("Joey", "Description1"));
        shelter.intakePet(new VirtualPet("Johnny", "Description2"));
        shelter.intakePet(new VirtualPet("Dee Dee", "Description3"));
        shelter.intakePet(new VirtualPet("Tommy", "Description4"));

        while (true) {
            displayMenu();
            int choice = Integer.parseInt(scanner.nextLine());

            switch (choice) {
                case 1:
                    shelter.feedAllPets();
                    break;
                case 2:
                    shelter.waterAllPets();
                    break;
                case 3:
                    playWithPet(shelter, scanner);
                    break;
                case 4:
                    adoptPet(shelter, scanner);
                    break;
                case 5:
                    admitPet(shelter, scanner);
                    break;
                case 6:
                    System.out.println("Goodbye!");
                    System.exit(0);
                    break;
                default:
                    System.out.println("Invalid choice. Try again.");
            }

            shelter.tickAllPets();
            displayPetStatus(shelter);
        }
    }

    private static void displayMenu() {
        System.out.println("What would you like to do next?");
        System.out.println("1. Feed the pets");
        System.out.println("2. Water the pets");
        System.out.println("3. Play with a pet");
        System.out.println("4. Adopt a pet");
        System.out.println("5. Admit a pet");
        System.out.println("6. Quit");
    }

    private static void displayPetStatus(VirtualPetShelter shelter) {
        System.out.println("\nThis is the status of your pets:\n");
        System.out.println("Name\t|Hunger\t|Thirst\t|Boredom");
        System.out.println("--------|-------|-------|-------");

        for (VirtualPet pet : shelter.getAllPets()) {
            System.out.println(pet.getName() + "\t|" + pet.getHunger() + "\t|" +
                    pet.getThirst() + "\t|" + pet.getBoredom());
        }
    }

    private static void playWithPet(VirtualPetShelter shelter, Scanner scanner) {
        System.out.println("Ok, so you'd like to play with a pet. Please choose one:");
        for (VirtualPet pet : shelter.getAllPets()) {
            System.out.print("[" + pet.getName() + "] ");
        }

        System.out.println("\nWhich pet would you like to play with?");
        String petName = scanner.nextLine();
        shelter.playWithPet(petName);
        System.out.println("Ok, you play with " + petName + ".");
    }

    private static void adoptPet(VirtualPetShelter shelter, Scanner scanner) {
        System.out.println("Ok, so you'd like to adopt a pet. Please choose one:");
        for (VirtualPet pet : shelter.getAllPets()) {
            System.out.print("[" + pet.getName() + "] ");
        }

        System.out.println("\nWhich pet would you like to adopt?");
        String petName = scanner.nextLine();
        VirtualPet adoptedPet = shelter.adoptPet(petName);
        System.out.println("Congratulations! You adopted " + petName + ".");
    }

    private static void admitPet(VirtualPetShelter shelter, Scanner scanner) {
        System.out.println("Ok, so you'd like to admit a pet.");
        System.out.println("Please enter the pet's name:");
        String petName = scanner.nextLine();
        System.out.println("Please enter the pet's description:");
        String petDescription = scanner.nextLine();

        VirtualPet newPet = new VirtualPet(petName, petDescription);
        shelter.intakePet(newPet);
        System.out.println("You admitted a new pet named " + petName + ".");
    }
}
